---
deployment:
  tasks:
    # Set the deployment path
    - export DEPLOYPATH=/home/wshaoen/public_html

    # Create backup of existing files (if any)
    - /bin/cp -R ${DEPLOYPATH} ${DEPLOYPATH}.backup

    # Clean the deployment directory
    - /bin/rm -rf ${DEPLOYPATH}/*

    # Install dependencies and build the application
    - /bin/npm install
    - /bin/npm run build

    # Copy the built files to the deployment path
    - /bin/cp -R * ${DEPLOYPATH}

    # # Copy other necessary files
    # - /bin/cp ./index.html ${DEPLOYPATH}
    # - /bin/cp ./src/assets/logos/kobodrop_favicon.png ${DEPLOYPATH}/src/assets/logos/kobodrop_favicon.png
    # - /bin/cp ./src/main.tsx ${DEPLOYPATH}/src/main.tsx
    # - /bin/cp ./src/index.css ${DEPLOYPATH}/src/index.css

    # Set proper permissions
    - /bin/chmod 755 ${DEPLOYPATH}
    - /bin/find ${DEPLOYPATH} -type d -exec /bin/chmod 755 {} \;
    - /bin/find ${DEPLOYPATH} -type f -exec /bin/chmod 644 {} \;