deployment:
  tasks:
    # Deploy the website to public_html
    - export DEPLOYPATH=/home/wshaoen/public_html/
    
    # Create backup of existing files (if any)
    - /bin/cp -R ${DEPLOYPATH} ${DEPLOYPATH}.backup
    
    # Clean the deployment directory
    - /bin/rm -rf ${DEPLOYPATH}/*
    
    # Deploy the build files
    # First, build your React application locally
    - /bin/npm install     # Install dependencies
    - /bin/npm run build   # Build the application
    
    # Copy the built files to the deployment path
    - /bin/cp -R ./dist/* ${DEPLOYPATH}
    
    # Copy other necessary files
    - /bin/cp .htaccess ${DEPLOYPATH}
    - /bin/cp robots.txt ${DEPLOYPATH}
    
    # Set proper permissions
    - /bin/chmod 755 ${DEPLOYPATH}
    - /bin/find ${DEPLOYPATH} -type d -exec /bin/chmod 755 {} \;
    - /bin/find ${DEPLOYPATH} -type f -exec /bin/chmod 644 {} \;